# discord api
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1518933099524788244/wh0sr5o7aeDrgZ7F9wyhkoh1PZ_Z5AxmluaGCu9TvplTA92VjF5UvYJ_Tv_D_aoQ9oQD"
# google api
OPENAI_API_KEY = "AIzaSyDAyotsgTTrjnnwvsFExbCOZRQDbAPGySk"
# excel link
DATABASE_URL = "https://docs.google.com/spreadsheets/d/1Lq006U0EeLffHQANz5TAKbTM0UJFHWIYrwFz1heUxAA/edit?usp=sharing"

