# discord api
DISCORD_WEBHOOK_URL = "MTQ5ODYzNzIwMzgzODg2MTM0Mw.GxB5FM.Ai4EMG99Uf1b9qciwEhvnL5YPJG8EVKzvD5GbQ"
# google api
OPENAI_API_KEY = "AIzaSyDAyotsgTTrjnnwvsFExbCOZRQDbAPGySk"
# excel link
DATABASE_URL = "https://docs.google.com/spreadsheets/d/1Lq006U0EeLffHQANz5TAKbTM0UJFHWIYrwFz1heUxAA/edit?usp=sharing"

